export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
// 定义别名
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
// 定义别名
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
